# Generated by Django 5.0 on 2024-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackform',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('comments', models.CharField()),
            ],
            options={
                'db_table': 'feedbackform',
            },
        ),
    ]
