# Generated by Django 5.0 on 2024-02-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0002_feedbackform'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.IntegerField()),
                ('comments', models.CharField()),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.DeleteModel(
            name='feedbackform',
        ),
    ]
